spring.application.name=springFrameworkFirstStep

## mysql connection info
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/study
spring.datasource.username=study_user
spring.datasource.password=studyuser123
